# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
# - dev

trigger:
  batch: true
  branches:
    include:
    - devops

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: shellScript
  displayName: 'Download shellScript file'
  inputs:
    secureFile: 'brainlitz_web_deploy.sh'

- script: |
    npm install
    npm run build:dev
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/dist.zip'
    replaceExistingArchive: true

# - task: CopyFiles@2
#   displayName: 'Copy /dist folder to Artifact directory'
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish dist.zip to System default working directory'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish shellScript to System default working directory'
  inputs:
    PathtoPublish: '$(shellScript.secureFilePath)'