# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    staging:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
          - apt-get update
          - apt-get install rsync -y     
          - rsync -avhze ssh $BITBUCKET_CLONE_DIR/dist/ htetshweyilin@13.229.235.46:/public_html/brainlitz-web/dist/
          - cat ./deploy.sh | ssh htetshweyilin@13.229.235.46